/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import constructor.Pet_supplies;
import Data.PetSupplieDB;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author pasindu
 */
public class Manager_Add_New_Pet_Supplie_Details1 extends javax.swing.JFrame {
    Pet_supplies pet_supplies;
    PetSupplieDB psDB=new PetSupplieDB();
    /**
     * Creates new form Add_New_Pet_Supplie_Details
     */
    public Manager_Add_New_Pet_Supplie_Details1() {
        initComponents();
        fillComboFromTxtFile();
    }
    public void fillComboFromTxtFile(){
        
        String filepath = "Category.txt";
        File file = new File(filepath);
        
        try {
            BufferedReader br = new BufferedReader (new FileReader(file));
            Object[] lines = br.lines().toArray();
            
            for(int i=0;i< lines.length;i++){
            
                String line = lines[i].toString();
                Category_ComboBox.addItem(line);
        }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Manager_Add_New_Pet_Supplie_Details1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Log_out_Button = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Txt_Price = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Txt_Discription = new javax.swing.JTextField();
        Txt_pet = new javax.swing.JTextField();
        Category_ComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Txt_Brand = new javax.swing.JTextField();
        Txt_Size = new javax.swing.JTextField();
        Txt_Metirial = new javax.swing.JTextField();
        Back_Button = new javax.swing.JButton();
        Exit_Button = new javax.swing.JButton();
        Submit_Button = new javax.swing.JButton();
        Txt_Color1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add 2.png"))); // NOI18N

        Log_out_Button.setBackground(new java.awt.Color(0, 102, 102));
        Log_out_Button.setForeground(new java.awt.Color(255, 255, 255));
        Log_out_Button.setText("Log out");
        Log_out_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Log_out_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_out_ButtonActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Log_out_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 347, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Log_out_Button)
                    .addComponent(jLabel11))
                .addGap(12, 12, 12))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 600));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Brand");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 80, 30));

        Txt_Price.setBackground(new java.awt.Color(0, 102, 102));
        Txt_Price.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Txt_Price.setForeground(new java.awt.Color(255, 255, 255));
        Txt_Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_PriceActionPerformed(evt);
            }
        });
        jPanel1.add(Txt_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 180, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Discription");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, -1, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Color");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 80, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Price");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 70, 30));

        Txt_Discription.setBackground(new java.awt.Color(0, 102, 102));
        Txt_Discription.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Txt_Discription.setForeground(new java.awt.Color(255, 255, 255));
        Txt_Discription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_DiscriptionActionPerformed(evt);
            }
        });
        jPanel1.add(Txt_Discription, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, 180, -1));

        Txt_pet.setBackground(new java.awt.Color(0, 102, 102));
        Txt_pet.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Txt_pet.setForeground(new java.awt.Color(255, 255, 255));
        Txt_pet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_petActionPerformed(evt);
            }
        });
        jPanel1.add(Txt_pet, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 180, -1));

        Category_ComboBox.setBackground(new java.awt.Color(0, 102, 102));
        Category_ComboBox.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Category_ComboBox.setForeground(new java.awt.Color(255, 255, 255));
        Category_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Category_ComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(Category_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 180, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Pet");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 80, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Category");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 120, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Size");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 80, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Metirial");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 90, 30));

        Txt_Brand.setBackground(new java.awt.Color(0, 102, 102));
        Txt_Brand.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Txt_Brand.setForeground(new java.awt.Color(255, 255, 255));
        Txt_Brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_BrandActionPerformed(evt);
            }
        });
        jPanel1.add(Txt_Brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 180, -1));

        Txt_Size.setBackground(new java.awt.Color(0, 102, 102));
        Txt_Size.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Txt_Size.setForeground(new java.awt.Color(255, 255, 255));
        Txt_Size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_SizeActionPerformed(evt);
            }
        });
        jPanel1.add(Txt_Size, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 180, -1));

        Txt_Metirial.setBackground(new java.awt.Color(0, 102, 102));
        Txt_Metirial.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Txt_Metirial.setForeground(new java.awt.Color(255, 255, 255));
        Txt_Metirial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_MetirialActionPerformed(evt);
            }
        });
        jPanel1.add(Txt_Metirial, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 180, -1));

        Back_Button.setBackground(new java.awt.Color(0, 102, 102));
        Back_Button.setForeground(new java.awt.Color(255, 255, 255));
        Back_Button.setText("Back");
        Back_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Back_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 70, 30));

        Exit_Button.setBackground(new java.awt.Color(0, 102, 102));
        Exit_Button.setForeground(new java.awt.Color(255, 255, 255));
        Exit_Button.setText("Exit");
        Exit_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 560, 70, 30));

        Submit_Button.setBackground(new java.awt.Color(0, 102, 102));
        Submit_Button.setForeground(new java.awt.Color(255, 255, 255));
        Submit_Button.setText("Submit");
        Submit_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Submit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Submit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 70, 30));

        Txt_Color1.setBackground(new java.awt.Color(0, 102, 102));
        Txt_Color1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Txt_Color1.setForeground(new java.awt.Color(255, 255, 255));
        Txt_Color1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Color1ActionPerformed(evt);
            }
        });
        jPanel1.add(Txt_Color1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 180, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/name2.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_PriceActionPerformed

    private void Txt_DiscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_DiscriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_DiscriptionActionPerformed

    private void Txt_petActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_petActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_petActionPerformed

    private void Category_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Category_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Category_ComboBoxActionPerformed

    private void Txt_BrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_BrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_BrandActionPerformed

    private void Txt_SizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_SizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_SizeActionPerformed

    private void Txt_MetirialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_MetirialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_MetirialActionPerformed

    private void Submit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_ButtonActionPerformed
        String pet = Txt_pet.getText();
        String category = Category_ComboBox.getSelectedItem().toString();
        String color = Txt_pet.getText();
        int price = Integer.parseInt(Txt_Price.getText());
        String brand = Txt_Brand.getText();
        String size = Txt_Size.getText();
        String metirial = Txt_Metirial.getText();
        String discription = Txt_Discription.getText();
        
        
        
        pet_supplies=new Pet_supplies(pet, category, color, price, brand, size, metirial, discription);
        
        boolean result=psDB.insert(pet_supplies);
        if (result)
            JOptionPane.showMessageDialog(null, "Adding scussfuly");
        else{
            JOptionPane.showMessageDialog(null, "Adding unscussfuly");
        }
    }//GEN-LAST:event_Submit_ButtonActionPerformed

    private void Txt_Color1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Color1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Color1ActionPerformed

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
 this.dispose();
    Manager_Menu  Manager_MenuFrame = new  Manager_Menu();
    Manager_MenuFrame.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_Back_ButtonActionPerformed

    private void Log_out_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_out_ButtonActionPerformed
     this.dispose();
    LogIn_Method  LogIn_MethodFrame = new  LogIn_Method();
    LogIn_MethodFrame.setVisible(true);  
        // TODO add your handling code here:
    }//GEN-LAST:event_Log_out_ButtonActionPerformed

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager_Add_New_Pet_Supplie_Details1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager_Add_New_Pet_Supplie_Details1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager_Add_New_Pet_Supplie_Details1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager_Add_New_Pet_Supplie_Details1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_Add_New_Pet_Supplie_Details1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JComboBox<String> Category_ComboBox;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JButton Log_out_Button;
    private javax.swing.JButton Submit_Button;
    private javax.swing.JTextField Txt_Brand;
    private javax.swing.JTextField Txt_Color1;
    private javax.swing.JTextField Txt_Discription;
    private javax.swing.JTextField Txt_Metirial;
    private javax.swing.JTextField Txt_Price;
    private javax.swing.JTextField Txt_Size;
    private javax.swing.JTextField Txt_pet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
